[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
network = "${RPC_URL}"

[etherscan]
base-sepolia = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options